import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    'guia-rapido',
    {
      type: 'category',
      label: '💼 Vendedor',
      collapsed: false,
      link: {type: 'doc', id: 'vendedor/index'},
      items: [
        'vendedor/meu-dia',
        'vendedor/pipeline',
        'vendedor/deals',
        'vendedor/cadencias',
        'vendedor/conversas',
        'vendedor/leads-quentes',
        'vendedor/metas',
        'vendedor/telefonia',
        'vendedor/faq',
      ],
    },
    {
      type: 'category',
      label: '🤝 Sucesso do Cliente',
      collapsed: true,
      link: {type: 'doc', id: 'cs/index'},
      items: [
        'cs/dashboard',
        'cs/clientes',
        'cs/health-score',
        'cs/churn',
        'cs/pesquisas',
        'cs/incidencias',
        'cs/playbooks',
        'cs/briefing',
        'cs/renovacoes',
        'cs/faq',
      ],
    },
    {
      type: 'category',
      label: '📊 Gestor',
      collapsed: true,
      link: {type: 'doc', id: 'gestor/index'},
      items: [
        'gestor/cockpit',
        'gestor/analytics',
        'gestor/pipelines-config',
        'gestor/usuarios',
        'gestor/campos-custom',
        'gestor/templates',
        'gestor/performance',
        'gestor/faq',
      ],
    },
    {
      type: 'category',
      label: '⚙️ Administrador',
      collapsed: true,
      link: {type: 'doc', id: 'admin/index'},
      items: [
        'admin/ia-config',
        'admin/conhecimento',
        'admin/custos-ia',
        'admin/benchmark',
        'admin/integracoes',
        'admin/importacao',
        'admin/saude-operacional',
        'admin/cron-jobs',
        'admin/multi-tenancy',
        'admin/faq',
      ],
    },
    {
      type: 'category',
      label: '🛠️ Desenvolvedor',
      collapsed: true,
      link: {type: 'doc', id: 'desenvolvedor/index'},
      items: [
        'desenvolvedor/stack',
        'desenvolvedor/edge-functions',
        'desenvolvedor/rls',
        'desenvolvedor/multi-tenancy',
        'desenvolvedor/sdr-ia',
        'desenvolvedor/cadence-engine',
        'desenvolvedor/webhooks',
        'desenvolvedor/api-reference',
        'desenvolvedor/testes',
        'desenvolvedor/adr',
      ],
    },
  ],
};

export default sidebars;
