-- Add new ICP values for MPuppe
ALTER TYPE public.icp_tipo ADD VALUE IF NOT EXISTS 'MPUPPE_FINTECH_REG' BEFORE 'MPUPPE_NAO_CLASSIFICADO';
ALTER TYPE public.icp_tipo ADD VALUE IF NOT EXISTS 'MPUPPE_DATA_HEAVY' BEFORE 'MPUPPE_NAO_CLASSIFICADO';
ALTER TYPE public.icp_tipo ADD VALUE IF NOT EXISTS 'MPUPPE_AI_PIONEER' BEFORE 'MPUPPE_NAO_CLASSIFICADO';
ALTER TYPE public.icp_tipo ADD VALUE IF NOT EXISTS 'MPUPPE_LEGAL_DEPT' BEFORE 'MPUPPE_NAO_CLASSIFICADO';

-- Add new ICP values for Axia
ALTER TYPE public.icp_tipo ADD VALUE IF NOT EXISTS 'AXIA_FINTECH_LAUNCH' BEFORE 'AXIA_NAO_CLASSIFICADO';
ALTER TYPE public.icp_tipo ADD VALUE IF NOT EXISTS 'AXIA_EXCHANGE_BUILDER' BEFORE 'AXIA_NAO_CLASSIFICADO';
ALTER TYPE public.icp_tipo ADD VALUE IF NOT EXISTS 'AXIA_ASSET_TOKENIZER' BEFORE 'AXIA_NAO_CLASSIFICADO';
ALTER TYPE public.icp_tipo ADD VALUE IF NOT EXISTS 'AXIA_MARKETPLACE_PAY' BEFORE 'AXIA_NAO_CLASSIFICADO';

-- Add new Persona values for MPuppe
ALTER TYPE public.persona_tipo ADD VALUE IF NOT EXISTS 'FUNDADOR_FINTECH';
ALTER TYPE public.persona_tipo ADD VALUE IF NOT EXISTS 'CTO_REGULACAO';
ALTER TYPE public.persona_tipo ADD VALUE IF NOT EXISTS 'JURIDICO_CORPORATIVO';

-- Add new Persona values for Axia
ALTER TYPE public.persona_tipo ADD VALUE IF NOT EXISTS 'EMPREENDEDOR_FINTECH';
ALTER TYPE public.persona_tipo ADD VALUE IF NOT EXISTS 'CTO_INFRAESTRUTURA';
ALTER TYPE public.persona_tipo ADD VALUE IF NOT EXISTS 'PRODUCT_MANAGER_CRYPTO';