
-- Migração 1: Adicionar novos valores aos enums
ALTER TYPE empresa_tipo ADD VALUE IF NOT EXISTS 'MPUPPE';
ALTER TYPE empresa_tipo ADD VALUE IF NOT EXISTS 'AXIA';
ALTER TYPE icp_tipo ADD VALUE IF NOT EXISTS 'MPUPPE_NAO_CLASSIFICADO';
ALTER TYPE icp_tipo ADD VALUE IF NOT EXISTS 'AXIA_NAO_CLASSIFICADO';
